[project]
name = "sre-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "voyger314", email = "1429796980@qq.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
sre-agent = "sre_agent:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
